import type { DocumentType, DocumentLanguage } from '@/features/documents/types';

/** Prompt version — increment when updating prompts to track which version generated a doc. */
export const DOCUMENT_PROMPT_VERSION = 'v1';

interface ToolContext {
  name: string;
  provider: string | null;
  category: string | null;
  description: string | null;
  usageContext: string | null;
  dataTypesProcessed: string[] | null;
  userCount: number | null;
  isCustomerFacing: boolean | null;
  automatedDecisions: boolean | null;
}

interface AssessmentContext {
  riskLevel: string;
  riskScore: number | null;
  findings: unknown[];
  recommendations: unknown[];
}

interface OrgContext {
  name: string;
  industry: string | null;
  country: string | null;
  employeeCount: number | null;
}

interface GenerationContext {
  tool: ToolContext | null;
  assessments: AssessmentContext[];
  org: OrgContext;
  additionalContext: string;
}

const LANG_INSTRUCTIONS: Record<DocumentLanguage, string> = {
  fr: 'Redige ENTIEREMENT en francais professionnel, precis et juridiquement solide.',
  en: 'Write ENTIRELY in professional English, precise and legally sound.',
};

const DISCLAIMER: Record<DocumentLanguage, string> = {
  fr: '> **Avertissement** : Ce document a ete genere par intelligence artificielle et doit etre valide par un professionnel juridique qualifie avant toute utilisation officielle.',
  en: '> **Disclaimer**: This document was generated by artificial intelligence and must be reviewed by a qualified legal professional before any official use.',
};

/**
 * System prompt shared by all document types.
 */
export function getDocumentSystemPrompt(language: DocumentLanguage): string {
  return `Tu es un expert senior en conformite reglementaire IA, protection des donnees (RGPD) et cybersecurite (NIS2, DORA).
Tu generes des documents de conformite professionnels, precis et juridiquement solides.

REGLES ABSOLUES :
1. ${LANG_INSTRUCTIONS[language]}
2. Utilise le format Markdown avec des titres hierarchiques (##, ###).
3. Sois exhaustif mais structure — chaque section doit etre clairement delimitee.
4. Cite les articles de loi pertinents quand c'est applicable.
5. Adapte le niveau de detail au contexte de l'entreprise et de l'outil.
6. Termine TOUJOURS le document avec l'avertissement suivant :

${DISCLAIMER[language]}`;
}

/**
 * Builds the user prompt for each document type.
 */
export function buildDocumentUserPrompt(
  type: DocumentType,
  regulation: string,
  context: GenerationContext,
  language: DocumentLanguage,
): string {
  const toolSection = context.tool
    ? `
## SYSTEME IA CONCERNE
- Nom : ${context.tool.name}
- Fournisseur : ${context.tool.provider ?? 'Non specifie'}
- Categorie : ${context.tool.category ?? 'Non specifiee'}
- Description : ${context.tool.description ?? 'Non specifiee'}
- Contexte d'utilisation : ${context.tool.usageContext ?? 'Non specifie'}
- Types de donnees traitees : ${context.tool.dataTypesProcessed?.join(', ') ?? 'Non specifies'}
- Nombre d'utilisateurs : ${context.tool.userCount ?? 'Non specifie'}
- Interaction directe clients : ${context.tool.isCustomerFacing ? 'Oui' : 'Non'}
- Decisions automatisees : ${context.tool.automatedDecisions ? 'Oui' : 'Non'}`
    : '\n## SYSTEME IA CONCERNE\nDocument global — aucun outil specifique.\n';

  const assessmentSection =
    context.assessments.length > 0
      ? `
## EVALUATION DES RISQUES EXISTANTE
${context.assessments
  .map(
    (a) => `- Niveau de risque : ${a.riskLevel} (score : ${a.riskScore ?? 'N/A'}/100)
  Findings : ${JSON.stringify(a.findings, null, 2)}
  Recommendations : ${JSON.stringify(a.recommendations, null, 2)}`,
  )
  .join('\n')}`
      : '';

  const orgSection = `
## ORGANISATION
- Nom : ${context.org.name}
- Industrie : ${context.org.industry ?? 'Non specifiee'}
- Pays : ${context.org.country ?? 'Non specifie'}
- Nombre d'employes : ${context.org.employeeCount ?? 'Non specifie'}`;

  const additionalSection = context.additionalContext
    ? `\n## INFORMATIONS SUPPLEMENTAIRES\n${context.additionalContext}`
    : '';

  const typePrompts = getTypeSpecificPrompt(type, regulation, language);

  return `${typePrompts}

${toolSection}
${orgSection}
${assessmentSection}
${additionalSection}

Genere le document complet maintenant. Utilise le format Markdown.`;
}

/**
 * Returns type-specific prompt instructions.
 */
function getTypeSpecificPrompt(
  type: DocumentType,
  regulation: string,
  language: DocumentLanguage,
): string {
  const lang = language === 'fr' ? 'francais' : 'anglais';

  const prompts: Record<DocumentType, string> = {
    impact_assessment: `Genere une Evaluation d'Impact relative a l'Intelligence Artificielle (AIPD / DPIA) complete.

Reglementation principale : ${regulation}

Le document DOIT suivre cette structure exacte :
1. **Informations generales** — Reference du document, date, version, responsable
2. **Description du systeme IA** — Fonctionnement, finalite, donnees traitees
3. **Necessite et proportionnalite** — Justification de l'utilisation de l'IA
4. **Evaluation des risques pour les droits et libertes** — Matrice des risques identifies
5. **Mesures de mitigation** — Actions correctives et preventives detaillees
6. **Consultation des parties prenantes** — DPO, utilisateurs, personnes concernees
7. **Avis du DPO** — (A completer par le DPO de l'organisation)
8. **Decision et plan d'action** — Calendrier de mise en oeuvre des mesures
9. **Annexes** — References legales, methodologie

Redige en ${lang}.`,

    transparency_notice: `Genere une Notice de Transparence IA complete.

Reglementation principale : ${regulation}

Le document DOIT suivre cette structure exacte :
1. **Objet de la notice** — Pourquoi cette notice existe
2. **Description du systeme IA** — Fonctionnement simplifie pour les utilisateurs
3. **Donnees collectees et traitees** — Quelles donnees, comment, pourquoi
4. **Finalites du traitement** — Objectifs de l'utilisation de l'IA
5. **Droits des personnes concernees** — Acces, rectification, opposition, explication
6. **Intervention humaine** — Role du controle humain dans le processus
7. **Limites du systeme** — Ce que l'IA ne peut pas faire, taux d'erreur connus
8. **Contact** — DPO, responsable du traitement
9. **Mise a jour** — Date de derniere revision

Redige en ${lang}, dans un langage clair et accessible au grand public.`,

    technical_doc: `Genere une Documentation Technique IA complete conforme a l'Article 11 du AI Act.

Reglementation principale : ${regulation}

Le document DOIT suivre cette structure exacte :
1. **Description generale du systeme** — Architecture, composants, flux de donnees
2. **Specifications techniques** — Modeles utilises, parametres, performances
3. **Donnees d'entrainement et de validation** — Jeux de donnees, biais connus, qualite
4. **Mesures de cybersecurite** — Protection des donnees, resilience, acces
5. **Systeme de gestion des risques** — Identification, evaluation, mitigation
6. **Controle humain** — Mecanismes de supervision et d'intervention
7. **Journalisation et tracabilite** — Logs, audit trail, monitoring
8. **Informations pour les deployers** — Guide d'utilisation, limites, precautions
9. **Conformite reglementaire** — Mapping des exigences vs implementation

Redige en ${lang}.`,

    risk_register: `Genere un Registre des Risques IA complet.

Reglementation principale : ${regulation}

Le document DOIT suivre cette structure exacte :
1. **Identification des risques** — Liste exhaustive des risques par categorie
2. **Evaluation des risques** — Probabilite, impact, score pour chaque risque
3. **Classification reglementaire** — Niveau de risque EU AI Act (inacceptable/haut/limite/minimal)
4. **Mesures de controle existantes** — Ce qui est deja en place
5. **Mesures de controle planifiees** — Actions a mettre en oeuvre
6. **Responsabilites** — Qui est responsable de chaque action
7. **Calendrier de revision** — Frequence de re-evaluation
8. **Historique des modifications** — Suivi des changements

Redige en ${lang}.`,

    bias_audit: `Genere un Rapport d'Audit de Biais Algorithmique complet.

Reglementation principale : ${regulation}

Le document DOIT suivre cette structure exacte :
1. **Perimetre de l'audit** — Systeme audite, objectifs, methodologie
2. **Donnees analysees** — Sources, representativite, biais potentiels
3. **Metriques de biais** — Indicateurs utilises (demographic parity, equalized odds, etc.)
4. **Resultats de l'analyse** — Biais detectes par attribut protege
5. **Impact sur les personnes concernees** — Consequences des biais identifies
6. **Recommandations de mitigation** — Actions correctives prioritaires
7. **Plan de suivi** — Monitoring continu, frequence de re-audit
8. **Conclusion et attestation** — Resume et engagement

Redige en ${lang}.`,

    data_processing_record: `Genere un Registre des Traitements de Donnees (Article 30 RGPD) complet.

Reglementation principale : ${regulation}

Le document DOIT suivre cette structure exacte :
1. **Identification du traitement** — Nom, reference, responsable
2. **Finalites du traitement** — Objectifs detailles
3. **Base legale** — Consentement, interet legitime, obligation legale, etc.
4. **Categories de donnees** — Donnees personnelles, sensibles, techniques
5. **Categories de personnes concernees** — Employes, clients, prospects, etc.
6. **Destinataires des donnees** — Internes, sous-traitants, transferts hors UE
7. **Duree de conservation** — Politique de retention par type de donnee
8. **Mesures de securite** — Techniques et organisationnelles (Article 32 RGPD)
9. **Analyse d'impact** — Resume de l'AIPD si applicable
10. **Transferts internationaux** — Garanties et mecanismes juridiques

Redige en ${lang}.`,

    conformity_declaration: `Genere une Declaration de Conformite CE pour systeme IA (Article 47 AI Act).

Reglementation principale : ${regulation}

Le document DOIT suivre cette structure exacte :
1. **Identification du fournisseur** — Nom, adresse, contact
2. **Identification du systeme IA** — Nom, version, reference unique
3. **Objet de la declaration** — Engagement de conformite
4. **Reglementations applicables** — Liste des textes (AI Act, RGPD, NIS2, DORA)
5. **Normes harmonisees appliquees** — ISO, IEEE, etc.
6. **Evaluation de conformite** — Procedure suivie (auto-evaluation, organisme notifie)
7. **Resultats** — Resume des evaluations, audits, tests
8. **Engagement** — Declaration formelle de conformite
9. **Signataire** — Nom, fonction, date, signature

Redige en ${lang}.`,

    custom: `Genere un document de conformite IA personnalise.

Reglementation principale : ${regulation}

Adapte la structure et le contenu aux informations fournies ci-dessous.
Inclus au minimum :
1. Un resume executif
2. Le contexte reglementaire
3. L'analyse detaillee
4. Les recommandations
5. Le plan d'action

Redige en ${lang}.`,
  };

  return prompts[type];
}
